---
- hosts: db
  become:  true
  gather_facts: no
  pre_tasks:
    - name: 'update apt'
      raw: sudo apt update -y
    - name: 'install python2'
      raw: sudo apt -y install python-simplejson
  vars:
    server_name: 'dev.mydomain.co.uk'
    sys_packages:
      - vim
  roles:
    - init
    - mysql

