---
- name: Install MySQL server
  sudo: yes
  apt:  pkg=mariadb-server state=latest

- name: Add root user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"

- name: Add deploy DB user and allow access to news_* databases
  mysql_user: name={{db_username}} password={{db_password}} host="%" priv=*.*:ALL state=present

- name: Create databases
  mysql_db: name={{database}} state=present collation=utf8_general_ci encoding=utf8