---
  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install basic system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - git
      - python-software-properties

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes

  - name: Install extra packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: sys_packages
